### ISSUE TITLE
issue-1-user-can-see-their-car

### ISSUE THREAD

**Issue by jsygo** [jsygo/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Put a background on the page
- [x] Add image of car to page
- [x] Make sure car is sized correctly
