### ISSUE TITLE
issue-2-user-can-turn-their-car

### ISSUE THREAD

**Issue by jsygo** [jsygo/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add event listener for `keydown` event
- [x] Add CSS classes for each direction the car needs to face
- [x] Add transitions for turning
- [x] Test functionality
- [x] Fix any bugs

**Comment by jsygo** [comment]
✅ Task List

- [x] Create data model that can hold which direction the car is currently facing
- [x] Add event listener for keydown event
- [x]  Add CSS classes for each direction the car needs to face
- [x] Add transitions for turning
- [x] Test functionality
- [x] Fix any bugs
