### ISSUE TITLE
issue-3-user-can-start-their-car

### ISSUE THREAD

**Issue by jsygo** [jsygo/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to data model to hold the car's x and y coordinates on the page
- [x] Add a conditional for space on the keydown event handler
- [x] #8
- [x] If user presses space, make the car move forward in the direction it's facing
- [x] Test functionality
- [x] Fix all bugs
