### ISSUE TITLE
issue-4-user-can-stop-their-car

### ISSUE THREAD

**Issue by jsygo** [jsygo/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

**Comment by jsygo** [comment]
## ✅ Task List

- [x] Add boolean to data model indicating whether or not the car is started
- [x] If car is started and user presses space, stop the car
- [x] Test functionality
- [x] Fix all bugs
